### ISSUE TITLE
Re-implement _write in a way which doesn't require close()

### ISSUE THREAD

**Issue by mekarpeles** [mekarpeles/lazydb#1]
def _write(self):
        """Crufty hack: Right now a new file handler is re-established
        every time a write is performed to ensure modifications to the
        shelve instance are saved / accepted after each atomic db opeartion."""
        self._db.close()
        self._db = self.open()

**Comment by Krokop** [comment]
I think it's done? https://github.com/mekarpeles/lazydb/commit/49c950b167221b5dd2eb67562220065d9c1bff95

**Comment by mekarpeles** [comment]
@Krokop Thanks for the contribution, confirmed using sync fixes the problem for me.

**Comment by Krokop** [comment]
so can upgrade __version__ of project and rebuild module on pypy? I want to use latest)

**Comment by mekarpeles** [comment]
@Krokop -- yes, doing so now. Thanks for the reminder!

**Comment by mekarpeles** [comment]
Done 0.1.80
